import { randomBytes } from "node:crypto";
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { defineNuxtModule } from "nuxt/kit";
import { isCI, isTest } from "std-env";

/**
 * Auto-generates ephemeral secrets required for test and CI builds.
 *
 * @onmax/nuxt-better-auth requires a non-empty, 32+ character secret; nuxt-og-image
 * requires an HMAC secret when strict mode is enabled. In production both are
 * supplied via environment variables. In CI the prebuilt server runs without those
 * env vars, so this module bakes random values into the build output at build time.
 *
 * Guards preserve any value already present (e.g. from a local .env file) so
 * local development is unaffected.
 */
export default defineNuxtModule({
	meta: {
		name: "wolfstar:test-secrets",
	},
	setup(_options, nuxt) {
		if (!isTest && !isCI) return;

		const envPath = join(nuxt.options.rootDir, ".env");
		const envContent = existsSync(envPath) ? readFileSync(envPath, "utf-8") : "";

		function resolveSecret(envKey: string): string {
			const match = envContent.match(new RegExp(`^${envKey}=(.+)$`, "m"));
			if (match?.[1]) return match[1];
			const value = randomBytes(32).toString("hex");
			appendFileSync(envPath, `\n# generated by wolfstar:test-secrets\n${envKey}=${value}\n`);
			return value;
		}

		const betterAuthSecret = resolveSecret("NUXT_BETTER_AUTH_SECRET");
		const imageProxySecret = resolveSecret("NUXT_IMAGE_PROXY_SECRET");

		// @onmax/nuxt-better-auth reads nuxt.options.runtimeConfig.betterAuthSecret
		// first, falling back to process.env.NUXT_BETTER_AUTH_SECRET. Baking it here
		// ensures the prebuilt server starts without the env var in the test process.
		const rc = nuxt.options.runtimeConfig as Record<string, unknown>;
		if (!rc.betterAuthSecret) {
			rc.betterAuthSecret = betterAuthSecret;
		}

		// nuxt.config.ts evaluated process.env.NUXT_IMAGE_PROXY_SECRET at config-eval
		// time, so nuxt.options.ogImage.security.strict is false when the env var was
		// absent. Patch it here before nuxt-og-image processes its configuration.
		const options = nuxt.options as unknown as {
			ogImage?: { security?: { strict?: boolean; secret?: string } };
		};
		if (!options.ogImage?.security?.strict) {
			options.ogImage ??= {};
			options.ogImage.security ??= {};
			options.ogImage.security.strict = true;
			options.ogImage.security.secret = imageProxySecret;
		}
	},
});
