services:
  wolfstar.rocks:
    image: ghrc.io/wolfstar-project/wolfstar.rocks:dev
    build: .
    container_name: wolfstar.rocks
    restart: no
    tty: true
    env_file:
      - .env
    ports:
      - "8281:8281"
