services:
  wolfstar.rocks:
    image: wolfstarbot/wolfstar.rocks:latest
    build: .
    container_name: wolfstar.rocks
    restart: 'no'
    tty: true
    env_file:
      - ./src/.env.production
    ports:
      - '8281:8281'
