#  This is the configuration file for Netlify
#  https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
command = "pnpm prisma:generate && pnpm run build" # build command
publish = "dist" # where the built project lives

[build.environment]
NODE_OPTIONS = '--max-old-space-size=4096'

[images]
remote_images = [
	"https:\\/\\/cdn.discordapp.com/.*",
	"https:\\/\\/media.discordapp.net/.*",
	"https:\\/\\/cdn.wolfstar.rocks/.*",
]

[[redirects]]
from = "https://repo.wolfstar.rocks/*"
to = "https://github.com/wolfstar-project/wolfstar.rocks/:splat"
status = 301
force = true

[[redirects]]
from = "https://chat.wolfstar.rocks"
to = "https://discord.gg/gqAnRyUXG8"
status = 301
force = true

[[redirects]]
from = "https://social.wolfstar.rocks/twitter"
to = "https://twitter.com/WolfstarApp"
status = 301
force = true
