packages: []

overrides:
  "@types/node": 22.13.14
  "@vercel/nft": ^0.30.3

catalogs:
  build:
    "@vite-pwa/assets-generator": ^1.0.2
    "@vite-pwa/nuxt": ^1.0.7
  cli:
    bumpp: ^10.3.1
    pncat: ^0.7.4
    taze: ^19.9.0
  database:
    "@prisma/adapter-pg": ^6.18.0
    "@prisma/client": ^6.18.0
    prisma: ^6.18.0
    prisma-json-types-generator: ^3.6.2
  dev:
    "@antfu/nip": ^0.1.0
    "@discordjs/collection": ^2.1.1
    "@discordjs/core": ^2.3.0
    "@netlify/nuxt": ^0.2.7
    "@nuxtjs/seo": ^3.2.2
    "@sapphire/bitfield": ^1.2.4
    "@sapphire/snowflake": ^3.5.5
    "@sapphire/time-utilities": ^1.7.14
    "@sapphire/utilities": ^3.18.2
    cz-conventional-changelog: ^3.3.0
    daisyui: ^5.3.10
    discord-api-types: ^0.38.31
    simple-git: ^3.29.0
    stale-dep: ^0.8.4
  e2e:
    playwright: ^1.56.1
  frontend:
    "@nuxt/ui": ^4.1.0
    "@pinia/nuxt": ^0.11.2
    motion-v: ^1.7.4
    pinia: ^3.0.3
  icons:
    "@iconify-json/emojione": ^1.2.3
    "@iconify-json/heroicons": ^1.2.3
    "@iconify-json/ic": ^1.2.4
    "@iconify-json/lucide": ^1.2.71
    "@iconify-json/ph": ^1.2.2
    "@nuxt/icon": ^2.1.0
  lint:
    "@antfu/eslint-config": ^6.1.0
    "@commitlint/cli": ^20.1.0
    "@commitlint/config-conventional": ^20.0.0
    "@nuxt/eslint": ^1.10.0
    "@sapphire/prettier-config": ^2.0.0
    eslint: ^9.38.0
    eslint-plugin-format: ^1.0.2
    eslint-plugin-package-json: ^0.59.1
    eslint-plugin-vuejs-accessibility: ^2.4.1
    husky: ^9.1.7
    lint-staged: ^16.2.6
    prettier: ^3.6.2
    prettier-plugin-css-order: ^2.1.2
    prettier-plugin-tailwindcss: ^0.7.1
  node:
    consola: ^3.4.2
    cross-env: ^10.1.0
    dotenv: ^17.2.3
    std-env: ^3.10.0
  prod:
    "@josephanson/nuxt-ai": ^0.1.6
    "@nuxt/image": ^1.11.0
    "@sentry/nuxt": ^10.22.0
    "@tanstack/pacer": ^0.15.4
    "@vee-validate/yup": ^4.15.1
    import-in-the-middle: ^2.0.0
    nuxt: ^4.2.0
    nuxt-authorization: ^0.3.5
    nuxt-vitalizer: ^2.0.0
    require-in-the-middle: ^8.0.1
    tailwind-merge: ^3.3.1
    tailwind-variants: ^3.1.1
    utility-types: ^3.11.0
    yup: ^1.7.1
  style:
    "@tailwindcss/typography": ^0.5.19
    postcss-nested: ^7.0.2
    tailwindcss: ^4.1.16
    tw-animate-css: ^1.4.0
  tsc:
    typescript: ~5.8.3
    vue-tsc: ^3.1.1
  utils:
    "@vueuse/core": ^13.9.0
    "@vueuse/integrations": ^13.9.0
    "@vueuse/nuxt": ^13.9.0
    "@vueuse/router": ^13.9.0
    fuse.js: ^7.1.0
    nuxt-auth-utils: ^0.5.25
    uuid: ^13.0.0
    zod: ^4.1.12

allowedDeprecatedVersions:
  glob: 7.2.3
  inflight: 1.0.6
  sourcemap-codec: 1.4.8

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - puppeteer
  - vue-demi

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - pncat
  - prisma
  - sharp
  - workerd

peerDependencyRules:
  allowedVersions:
    inflight: 1.0.6
    typescript: 5.8.3
    vue-tsc: ^3.0.7
