packages: []

overrides:
  "@types/node": 22.13.14
  "@vercel/nft": ^0.30.1

patchedDependencies:
  prisma: patches/prisma.patch

catalogs:
  build:
    "@vite-pwa/nuxt": ^1.0.4
    unplugin-unused: ^0.5.3
  cli:
    "@antfu/nip": ^0.1.0
    cross-env: ^10.0.0
    pncat: ^0.5.4
    taze: ^19.6.0
  dev:
    "@discordjs/collection": ^2.1.1
    "@discordjs/core": ^2.2.2
    "@nuxt/scripts": ^0.11.13
    "@nuxthub/core": ^0.9.0
    "@nuxtjs/seo": ^3.1.0
    "@sentry/nuxt": ^10.11.0
    daisyui: ^5.1.12
    discord-api-types: ^0.38.25
    nuxt-auth-utils: ^0.5.24
    simple-git: ^3.28.0
    std-env: ^3.9.0
    typescript: ~5.8.3
    vue-tsc: ^3.0.7
    wrangler: ^4.37.0
  frontend:
    "@nuxt/image": ^1.11.0
    "@nuxt/ui": 4.0.0-alpha.1
  icons:
    "@iconify-json/heroicons": ^1.2.2
    "@iconify-json/ic": ^1.2.4
    "@iconify-json/lucide": ^1.2.68
    "@iconify-json/ph": ^1.2.2
    "@nuxt/icon": ^2.0.0
  lint:
    "@antfu/eslint-config": ^5.3.0
    "@commitlint/cli": ^19.8.1
    "@commitlint/config-conventional": ^19.8.1
    "@nuxt/eslint": ^1.9.0
    "@sapphire/prettier-config": ^2.0.0
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-package-json: ^0.56.3
    husky: ^9.1.7
    lint-staged: ^16.1.6
    prettier: ^3.6.2
    prettier-plugin-css-order: ^2.1.2
    prettier-plugin-tailwindcss: ^0.6.14
  prod:
    "@pinia/nuxt": ^0.11.2
    "@prisma/adapter-pg": ~6.16.1
    "@prisma/client": ~6.16.1
    "@tanstack/pacer": ^0.15.2
    consola: ^3.4.2
    dotenv: ^17.2.2
    fuse.js: ^7.1.0
    import-in-the-middle: ^1.14.2
    motion-v: ^1.7.1
    nuxt: ^4.1.2
    nuxt-authorization: ^0.3.5
    nuxt-security: ^2.4.0
    nuxt-vitalizer: ^2.0.0
    nuxt-vue-dragscroll: ^1.0.1
    pinia: ^3.0.3
    prisma: ~6.16.1
    prisma-json-types-generator: ^3.6.0
    stale-dep: ^0.8.3
    tailwind-variants: ^3.1.1
    utility-types: ^3.11.0
  style:
    "@tailwindcss/typography": ^0.5.16
    postcss-nested: ^7.0.2
    postcss-nesting: ^13.0.2
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.13
    tw-animate-css: ^1.3.8
  test:
    playwright: ^1.55.0
  utils:
    "@sapphire/bitfield": ^1.2.4
    "@sapphire/result": ^2.7.2
    "@sapphire/snowflake": ^3.5.5
    "@sapphire/time-utilities": ^1.7.14
    "@sapphire/utilities": ^3.18.2
    "@vee-validate/yup": ^4.15.1
    "@vueuse/core": ^13.9.0
    "@vueuse/integrations": ^13.9.0
    "@vueuse/motion": ^3.0.3
    "@vueuse/nuxt": ^13.9.0
    "@vueuse/router": ^13.9.0
    clsx: ^2.1.1
    yup: ^1.7.0
    zod: ^4.1.8

allowedDeprecatedVersions:
  glob: 7.2.3
  inflight: 1.0.6
  sourcemap-codec: 1.4.8

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - pncat
  - prisma
  - sharp
  - workerd

peerDependencyRules:
  allowedVersions:
    inflight: 1.0.6
    typescript: 5.8.3
    vue-tsc: ^2.2.10
