export default {
	compoundVariants: [
		{
			class: "has-focus:bg-elevated",
			multiple: true,
			variant: "soft",
		},
		{
			class: "has-focus:bg-elevated",
			multiple: true,
			variant: "ghost",
		},
		{
			class: "has-focus-visible:ring-2 has-focus-visible:ring-primary",
			color: "primary",
			multiple: true,
			variant: ["outline", "subtle"],
		},
		{
			class: "has-focus-visible:ring-2 has-focus-visible:ring-neutral",
			color: "neutral",
			multiple: true,
			variant: ["outline", "subtle"],
		},
		{
			class: "focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary",
			color: "primary",
			variant: ["outline", "subtle"],
		},
		{
			class: "ring ring-inset ring-primary",
			color: "primary",
			highlight: true,
		},
		{
			class: "focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-neutral",
			color: "neutral",
			variant: ["outline", "subtle"],
		},
		{
			class: "ring ring-inset ring-neutral",
			color: "neutral",
			highlight: true,
		},
		{
			class: "ring ring-inset ring-secondary",
			color: "secondary",
			highlight: true,
		},
		{
			class: "ring ring-inset ring-success",
			color: "success",
			highlight: true,
		},
		{
			class: "ring ring-inset ring-info",
			color: "info",
			highlight: true,
		},
		{
			class: "ring ring-inset ring-warning",
			color: "warning",
			highlight: true,
		},
		{
			class: "ring ring-inset ring-error",
			color: "error",
			highlight: true,
		},
		{
			class: "ps-7",
			leading: true,
			size: "xs",
		},
		{
			class: "ps-8",
			leading: true,
			size: "sm",
		},
		{
			class: "ps-9",
			leading: true,
			size: "md",
		},
		{
			class: "ps-10",
			leading: true,
			size: "lg",
		},
		{
			class: "ps-11",
			leading: true,
			size: "xl",
		},
		{
			class: "pe-7",
			size: "xs",
			trailing: true,
		},
		{
			class: "pe-8",
			size: "sm",
			trailing: true,
		},
		{
			class: "pe-9",
			size: "md",
			trailing: true,
		},
		{
			class: "pe-10",
			size: "lg",
			trailing: true,
		},
		{
			class: "pe-11",
			size: "xl",
			trailing: true,
		},
		{
			class: {
				leadingIcon: "animate-spin",
			},
			leading: true,
			loading: true,
		},
		{
			class: {
				trailingIcon: "animate-spin",
			},
			leading: false,
			loading: true,
			trailing: true,
		},
	],
	defaultVariants: {
		color: "primary",
		size: "md",
		variant: "outline",
	},
	slots: {
		arrow: "fill-base-100",
		base: ["input"],
		content:
			"max-h-60 w-(--reka-combobox-trigger-width) bg-base-100 shadow-lg rounded-md ring ring-base-300 overflow-hidden data-[state=open]:animate-[scale-in_100ms_ease-out] data-[state=closed]:animate-[scale-out_100ms_ease-in] origin-(--reka-combobox-content-transform-origin) pointer-events-auto flex flex-col",
		empty: "text-center text-base-content bg-base-300",
		group: "p-1 isolate",
		item: [
			"group relative w-full flex items-center gap-1.5 p-1.5 text-sm select-none outline-none before:absolute before:z-[-1] before:inset-px before:rounded-md data-disabled:cursor-not-allowed data-disabled:opacity-75 text-base-content data-highlighted:not-data-disabled:text-base-content data-highlighted:not-data-disabled:before:bg-base-200",
			"transition-colors before:transition-colors",
		],
		itemLabel: "truncate",
		itemLeadingAvatar: "shrink-0",
		itemLeadingAvatarSize: "",
		itemLeadingChip: "shrink-0",
		itemLeadingChipSize: "",
		itemLeadingIcon: [
			"shrink-0 text-base-content/50 group-data-highlighted:not-group-data-disabled:text-base-content",
			"transition-colors",
		],
		itemTrailing: "ms-auto inline-flex gap-1.5 items-center",
		itemTrailingIcon: "shrink-0",
		label: "font-semibold text-base-content",
		leading: "absolute inset-y-0 start-0 flex items-center",
		leadingAvatar: "shrink-0",
		leadingAvatarSize: "",
		leadingIcon: "shrink-0 text-base-content/50",
		root: "relative inline-flex items-center",
		separator: "-mx-1 my-1 h-px bg-base-300",
		tagsInput:
			"flex-1 border-0 bg-transparent placeholder:text-base-content/50 focus:outline-none disabled:cursor-not-allowed disabled:opacity-75",
		tagsItem:
			"px-1.5 py-0.5 rounded-sm font-medium inline-flex items-center gap-0.5 ring ring-inset ring-base-300 bg-base-200 text-base-content data-disabled:cursor-not-allowed data-disabled:opacity-75",
		tagsItemDelete: [
			"inline-flex items-center rounded-xs text-base-content/50 hover:text-base-content hover:bg-base-300/75 disabled:pointer-events-none",
			"transition-colors",
		],
		tagsItemDeleteIcon: "shrink-0",
		tagsItemText: "truncate",
		trailing:
			"group absolute inset-y-0 end-0 flex items-center disabled:cursor-not-allowed disabled:opacity-75",
		trailingIcon: "shrink-0 text-base-content/50",
		viewport: "relative divide-y divide-base-200 scroll-py-1 overflow-y-auto flex-1",
	},
	variants: {
		buttonGroup: {
			horizontal: {
				base: "group-not-only:group-first:rounded-e-none group-not-only:group-last:rounded-s-none group-not-last:group-not-first:rounded-none",
				root: "group has-focus-visible:z-[1]",
			},
			vertical: {
				base: "group-not-only:group-first:rounded-b-none group-not-only:group-last:rounded-t-none group-not-last:group-not-first:rounded-none",
				root: "group has-focus-visible:z-[1]",
			},
		},
		color: {
			error: "input-error",
			info: "input-info",
			neutral: "input-neutral",
			primary: "input-primary",
			secondary: "input-secondary",
			success: "input-success",
			warning: "input-warning",
		},
		highlight: {
			true: "",
		},
		leading: {
			true: "",
		},
		loading: {
			true: "",
		},
		multiple: {
			false: {
				base: "w-full border-0 placeholder:text-base-content/50 focus:outline-none disabled:cursor-not-allowed disabled:opacity-75",
			},
			true: {
				root: "flex flex-wrap",
			},
		},
		size: {
			lg: {
				base: "input-lg",
				empty: "p-2 text-sm",
				item: "p-2 text-sm gap-2",
				itemLeadingAvatarSize: "2xs",
				itemLeadingChip: "size-5",
				itemLeadingChipSize: "md",
				itemLeadingIcon: "size-5",
				itemTrailingIcon: "size-5",
				label: "p-2 text-xs gap-2",
				leading: "ps-2",
				leadingAvatarSize: "2xs",
				leadingIcon: "size-5",
				tagsItem: "text-xs",
				tagsItemDeleteIcon: "size-3.5",
				trailing: "pe-3",
				trailingIcon: "size-5",
			},
			md: {
				base: "input-md",
				empty: "p-1.5 text-sm",
				item: "p-1.5 text-sm gap-1.5",
				itemLeadingAvatarSize: "2xs",
				itemLeadingChip: "size-5",
				itemLeadingChipSize: "md",
				itemLeadingIcon: "size-5",
				itemTrailingIcon: "size-5",
				label: "p-1.5 text-xs gap-1.5",
				leading: "ps-2.5",
				leadingAvatarSize: "2xs",
				leadingIcon: "size-5",
				tagsItem: "text-xs",
				tagsItemDeleteIcon: "size-3.5",
				trailing: "pe-2.5",
				trailingIcon: "size-5",
			},
			sm: {
				base: "input-sm",
				empty: "p-1.5 text-xs",
				item: "p-1.5 text-xs gap-1.5",
				itemLeadingAvatarSize: "3xs",
				itemLeadingChip: "size-4",
				itemLeadingChipSize: "sm",
				itemLeadingIcon: "size-4",
				itemTrailingIcon: "size-4",
				label: "p-1.5 text-[10px]/3 gap-1.5",
				leading: "ps-2.5",
				leadingAvatarSize: "3xs",
				leadingIcon: "size-4",
				tagsItem: "text-[10px]/3",
				tagsItemDeleteIcon: "size-3",
				trailing: "pe-2.5",
				trailingIcon: "size-4",
			},
			xl: {
				base: "input-xl",
				empty: "p-2 text-base",
				item: "p-2 text-base gap-2",
				itemLeadingAvatarSize: "xs",
				itemLeadingChip: "size-6",
				itemLeadingChipSize: "lg",
				itemLeadingIcon: "size-6",
				itemTrailingIcon: "size-6",
				label: "p-2 text-sm gap-2",
				leading: "ps-3",
				leadingAvatarSize: "xs",
				leadingIcon: "size-6",
				tagsItem: "text-sm",
				tagsItemDeleteIcon: "size-4",
				trailing: "pe-3",
				trailingIcon: "size-6",
			},
			xs: {
				base: "input-xs",
				empty: "p-1 text-xs",
				item: "p-1 text-xs gap-1",
				itemLeadingAvatarSize: "3xs",
				itemLeadingChip: "size-4",
				itemLeadingChipSize: "sm",
				itemLeadingIcon: "size-4",
				itemTrailingIcon: "size-4",
				label: "p-1 text-[10px]/3 gap-1",
				leading: "ps-2",
				leadingAvatarSize: "3xs",
				leadingIcon: "size-4",
				tagsItem: "text-[10px]/3",
				tagsItemDeleteIcon: "size-3",
				trailing: "pe-2",
				trailingIcon: "size-4",
			},
		},
		trailing: {
			true: "",
		},
		type: {
			file: "file:me-1.5 file:font-medium file:text-base-content/50 file:outline-none",
		},
		variant: {
			ghost: "text-base-content bg-transparent hover:bg-base-200 focus:bg-base-200 disabled:bg-transparent dark:disabled:bg-transparent",
			none: "text-base-content bg-transparent",
			outline: "text-base-content bg-base-100 ring ring-inset ring-base-300",
			soft: "text-base-content bg-base-200/50 hover:bg-base-200 focus:bg-base-200 disabled:bg-base-200/50",
			subtle: "text-base-content bg-base-200 ring ring-inset ring-base-300",
		},
	},
};
