export default {
  slots: {
    root: "relative inline-flex items-center",
    base: [
      "input",
    ],
    leading: "absolute inset-y-0 start-0 flex items-center",
    leadingIcon: "shrink-0 text-base-content/50",
    leadingAvatar: "shrink-0",
    leadingAvatarSize: "",
    trailing: "group absolute inset-y-0 end-0 flex items-center disabled:cursor-not-allowed disabled:opacity-75",
    trailingIcon: "shrink-0 text-base-content/50",
    arrow: "fill-base-100",
    content: "max-h-60 w-(--reka-combobox-trigger-width) bg-base-100 shadow-lg rounded-md ring ring-base-300 overflow-hidden data-[state=open]:animate-[scale-in_100ms_ease-out] data-[state=closed]:animate-[scale-out_100ms_ease-in] origin-(--reka-combobox-content-transform-origin) pointer-events-auto flex flex-col",
    viewport: "relative divide-y divide-base-200 scroll-py-1 overflow-y-auto flex-1",
    group: "p-1 isolate",
    empty: "text-center text-base-content bg-base-300",
    label: "font-semibold text-base-content",
    separator: "-mx-1 my-1 h-px bg-base-300",
    item: [
      "group relative w-full flex items-center gap-1.5 p-1.5 text-sm select-none outline-none before:absolute before:z-[-1] before:inset-px before:rounded-md data-disabled:cursor-not-allowed data-disabled:opacity-75 text-base-content data-highlighted:not-data-disabled:text-base-content data-highlighted:not-data-disabled:before:bg-base-200",
      "transition-colors before:transition-colors",
    ],
    itemLeadingIcon: [
      "shrink-0 text-base-content/50 group-data-highlighted:not-group-data-disabled:text-base-content",
      "transition-colors",
    ],
    itemLeadingAvatar: "shrink-0",
    itemLeadingAvatarSize: "",
    itemLeadingChip: "shrink-0",
    itemLeadingChipSize: "",
    itemTrailing: "ms-auto inline-flex gap-1.5 items-center",
    itemTrailingIcon: "shrink-0",
    itemLabel: "truncate",
    tagsItem: "px-1.5 py-0.5 rounded-sm font-medium inline-flex items-center gap-0.5 ring ring-inset ring-base-300 bg-base-200 text-base-content data-disabled:cursor-not-allowed data-disabled:opacity-75",
    tagsItemText: "truncate",
    tagsItemDelete: [
      "inline-flex items-center rounded-xs text-base-content/50 hover:text-base-content hover:bg-base-300/75 disabled:pointer-events-none",
      "transition-colors",
    ],
    tagsItemDeleteIcon: "shrink-0",
    tagsInput: "flex-1 border-0 bg-transparent placeholder:text-base-content/50 focus:outline-none disabled:cursor-not-allowed disabled:opacity-75",
  },
  variants: {
    buttonGroup: {
      horizontal: {
        root: "group has-focus-visible:z-[1]",
        base: "group-not-only:group-first:rounded-e-none group-not-only:group-last:rounded-s-none group-not-last:group-not-first:rounded-none",
      },
      vertical: {
        root: "group has-focus-visible:z-[1]",
        base: "group-not-only:group-first:rounded-b-none group-not-only:group-last:rounded-t-none group-not-last:group-not-first:rounded-none",
      },
    },
    size: {
      xs: {
        base: "input-xs",
        leading: "ps-2",
        trailing: "pe-2",
        leadingIcon: "size-4",
        leadingAvatarSize: "3xs",
        trailingIcon: "size-4",
        label: "p-1 text-[10px]/3 gap-1",
        item: "p-1 text-xs gap-1",
        itemLeadingIcon: "size-4",
        itemLeadingAvatarSize: "3xs",
        itemLeadingChip: "size-4",
        itemLeadingChipSize: "sm",
        itemTrailingIcon: "size-4",
        tagsItem: "text-[10px]/3",
        tagsItemDeleteIcon: "size-3",
        empty: "p-1 text-xs",
      },
      sm: {
        base: "input-sm",
        leading: "ps-2.5",
        trailing: "pe-2.5",
        leadingIcon: "size-4",
        leadingAvatarSize: "3xs",
        trailingIcon: "size-4",
        label: "p-1.5 text-[10px]/3 gap-1.5",
        item: "p-1.5 text-xs gap-1.5",
        itemLeadingIcon: "size-4",
        itemLeadingAvatarSize: "3xs",
        itemLeadingChip: "size-4",
        itemLeadingChipSize: "sm",
        itemTrailingIcon: "size-4",
        tagsItem: "text-[10px]/3",
        tagsItemDeleteIcon: "size-3",
        empty: "p-1.5 text-xs",
      },
      md: {
        base: "input-md",
        leading: "ps-2.5",
        trailing: "pe-2.5",
        leadingIcon: "size-5",
        leadingAvatarSize: "2xs",
        trailingIcon: "size-5",
        label: "p-1.5 text-xs gap-1.5",
        item: "p-1.5 text-sm gap-1.5",
        itemLeadingIcon: "size-5",
        itemLeadingAvatarSize: "2xs",
        itemLeadingChip: "size-5",
        itemLeadingChipSize: "md",
        itemTrailingIcon: "size-5",
        tagsItem: "text-xs",
        tagsItemDeleteIcon: "size-3.5",
        empty: "p-1.5 text-sm",
      },
      lg: {
        base: "input-lg",
        leading: "ps-2",
        trailing: "pe-3",
        leadingIcon: "size-5",
        leadingAvatarSize: "2xs",
        trailingIcon: "size-5",
        label: "p-2 text-xs gap-2",
        item: "p-2 text-sm gap-2",
        itemLeadingIcon: "size-5",
        itemLeadingAvatarSize: "2xs",
        itemLeadingChip: "size-5",
        itemLeadingChipSize: "md",
        itemTrailingIcon: "size-5",
        tagsItem: "text-xs",
        tagsItemDeleteIcon: "size-3.5",
        empty: "p-2 text-sm",
      },
      xl: {
        base: "input-xl",
        leading: "ps-3",
        trailing: "pe-3",
        leadingIcon: "size-6",
        leadingAvatarSize: "xs",
        trailingIcon: "size-6",
        label: "p-2 text-sm gap-2",
        item: "p-2 text-base gap-2",
        itemLeadingIcon: "size-6",
        itemLeadingAvatarSize: "xs",
        itemLeadingChip: "size-6",
        itemLeadingChipSize: "lg",
        itemTrailingIcon: "size-6",
        tagsItem: "text-sm",
        tagsItemDeleteIcon: "size-4",
        empty: "p-2 text-base",
      },
    },
    variant: {
      outline: "text-base-content bg-base-100 ring ring-inset ring-base-300",
      soft: "text-base-content bg-base-200/50 hover:bg-base-200 focus:bg-base-200 disabled:bg-base-200/50",
      subtle: "text-base-content bg-base-200 ring ring-inset ring-base-300",
      ghost: "text-base-content bg-transparent hover:bg-base-200 focus:bg-base-200 disabled:bg-transparent dark:disabled:bg-transparent",
      none: "text-base-content bg-transparent",
    },
    color: {
      primary: "input-primary",
      secondary: "input-secondary",
      success: "input-success",
      info: "input-info",
      warning: "input-warning",
      error: "input-error",
      neutral: "input-neutral",
    },
    leading: {
      true: "",
    },
    trailing: {
      true: "",
    },
    loading: {
      true: "",
    },
    highlight: {
      true: "",
    },
    type: {
      file: "file:me-1.5 file:font-medium file:text-base-content/50 file:outline-none",
    },
    multiple: {
      true: {
        root: "flex flex-wrap",
      },
      false: {
        base: "w-full border-0 placeholder:text-base-content/50 focus:outline-none disabled:cursor-not-allowed disabled:opacity-75",
      },
    },
  },
  compoundVariants: [
    {
      variant: "soft",
      multiple: true,
      class: "has-focus:bg-elevated",
    },
    {
      variant: "ghost",
      multiple: true,
      class: "has-focus:bg-elevated",
    },
    {
      color: "primary",
      multiple: true,
      variant: [
        "outline",
        "subtle",
      ],
      class: "has-focus-visible:ring-2 has-focus-visible:ring-primary",
    },
    {
      color: "neutral",
      multiple: true,
      variant: [
        "outline",
        "subtle",
      ],
      class: "has-focus-visible:ring-2 has-focus-visible:ring-neutral",
    },
    {
      color: "primary",
      variant: [
        "outline",
        "subtle",
      ],
      class: "focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary",
    },
    {
      color: "primary",
      highlight: true,
      class: "ring ring-inset ring-primary",
    },
    {
      color: "neutral",
      variant: [
        "outline",
        "subtle",
      ],
      class: "focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-neutral",
    },
    {
      color: "neutral",
      highlight: true,
      class: "ring ring-inset ring-neutral",
    },
    {
      color: "secondary",
      highlight: true,
      class: "ring ring-inset ring-secondary",
    },
    {
      color: "success",
      highlight: true,
      class: "ring ring-inset ring-success",
    },
    {
      color: "info",
      highlight: true,
      class: "ring ring-inset ring-info",
    },
    {
      color: "warning",
      highlight: true,
      class: "ring ring-inset ring-warning",
    },
    {
      color: "error",
      highlight: true,
      class: "ring ring-inset ring-error",
    },
    {
      leading: true,
      size: "xs",
      class: "ps-7",
    },
    {
      leading: true,
      size: "sm",
      class: "ps-8",
    },
    {
      leading: true,
      size: "md",
      class: "ps-9",
    },
    {
      leading: true,
      size: "lg",
      class: "ps-10",
    },
    {
      leading: true,
      size: "xl",
      class: "ps-11",
    },
    {
      trailing: true,
      size: "xs",
      class: "pe-7",
    },
    {
      trailing: true,
      size: "sm",
      class: "pe-8",
    },
    {
      trailing: true,
      size: "md",
      class: "pe-9",
    },
    {
      trailing: true,
      size: "lg",
      class: "pe-10",
    },
    {
      trailing: true,
      size: "xl",
      class: "pe-11",
    },
    {
      loading: true,
      leading: true,
      class: {
        leadingIcon: "animate-spin",
      },
    },
    {
      loading: true,
      leading: false,
      trailing: true,
      class: {
        trailingIcon: "animate-spin",
      },
    },
  ],
  defaultVariants: {
    size: "md",
    color: "primary",
    variant: "outline",
  },
};
