import type { Locale as I18nLocale } from "nuxt-i18n-micro";

type Locale = I18nLocale["code"];
type Directions = NonNullable<I18nLocale["dir"]>;

/**
 * Translation status data generated by the Lunaria build.
 */
export interface I18nStatus {
	/** ISO timestamp when this status was generated */
	generatedAt: string;
	/** The source locale (English) */
	sourceLocale: {
		lang: Locale;
		label: string;
		totalKeys: number;
	};
	/** Status for each target locale */
	locales: I18nLocaleStatus[];
}

export interface I18nLocaleStatus {
	/** Locale code (e.g. 'es-ES') */
	lang: Locale;
	/** Display name (e.g. 'Español') */
	label: string;
	dir: Directions;
	totalKeys: number;
	/** Number of completed translations */
	completedKeys: number;
	/** List of missing key paths (dot notation) */
	missingKeys: string[];
	/** Completion percentage (0-100) */
	percentComplete: number;
	/** GitHub URL to edit this locale's translation file */
	githubEditUrl: string;
	/** GitHub URL to view history of this locale's translation file */
	githubHistoryUrl: string;
}
