import type { Directions, LocaleObject } from "@nuxtjs/i18n";

type Locale = LocaleObject["code"];

/**
 * Translation status data generated by the Lunaria build.
 */
export interface I18nStatus {
	/** ISO timestamp when this status was generated */
	generatedAt: string;
	/** The source locale (English) */
	sourceLocale: {
		lang: Locale;
		label: string;
		totalKeys: number;
	};
	/** Status for each target locale */
	locales: I18nLocaleStatus[];
}

export interface I18nLocaleStatus {
	/** Locale code (e.g. 'es-ES') */
	lang: Locale;
	/** Display name (e.g. 'Español') */
	label: string;
	dir: Directions;
	totalKeys: number;
	completedKeys: number;
	/** List of missing key paths (dot notation) */
	missingKeys: string[];
	/** Completion percentage (0-100) */
	percentComplete: number;
	githubEditUrl: string;
	githubHistoryUrl: string;
}
