/**
 * Minimal stub for `#server/database/generated/client` used in unit tests.
 *
 * The real module is generated by `prisma generate` and is not checked in.
 * This stub provides just enough type-shape for unit test files that import
 * from the generated client; the actual values are always replaced by
 * `vi.mock()` factories in the test files themselves.
 */
import { PrismaClientKnownRequestError } from "@prisma/client/runtime/client";

export const Prisma = {
	TransactionIsolationLevel: { Serializable: "Serializable" } as Record<string, string>,
	PrismaClientKnownRequestError,
};

export { PrismaClientKnownRequestError };
