# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

permissions:
  contents: read

jobs:
  code:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # 4e1c8eafbd745f64b1ef30a7d7ed7965034c486c
        name: 🟧 Install pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔠 Fix lint errors
        run: pnpm vp run lint:fix

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
