# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  code:
    name: 🤖 Autofix code
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: voidzero-dev/setup-vp@2dec1e33f4ab2c6d5bce1b0c4607961bb1a3f7a1 # v1.12.0
        with:
          node-version: lts/*
          cache: true
          sfw: true

      - name: 🔠 Fix lint errors
        run: vp run lint:fix

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
