name: chromatic

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  chromatic:
    name: 📚 Chromatic
    runs-on: ubuntu-24.04-arm

    steps:
      - name: ☑️ Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false

      - uses: voidzero-dev/setup-vp@143f5f385f39b1b753ffed1a01ad443811855c8b # v1.16.1
        with:
          node-version: lts/*
          cache: true
          sfw: true

      - name: 🧪 Run Chromatic Visual and Accessibility Tests
        uses: chromaui/action@1bbb5819252d9782cb7d77122d9becae467def18 # v16.10.1
        with:
          buildCommand: vp run build-storybook
          outputDir: storybook-static
        env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          CHROMATIC_SLUG: ${{ github.repository }}
