# https://docs.github.com/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
# credit to: https://github.com/discordjs/discord.js/blob/main/.github/workflows/cleanup-cache.yml
name: Cleanup caches
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number to clean caches for (manual runs)
        required: true
jobs:
  cleanup:
    name: Cleanup caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup caches
        run: |
          gh extension install actions/gh-actions-cache

          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number || github.event.inputs.pr_number }}"
          BRANCH_REFS=()

          if [[ -n "$PR_NUMBER" ]]; then
            BRANCH_REFS+=("refs/pull/$PR_NUMBER/merge")
            BRANCH_REFS+=("refs/pull/$PR_NUMBER/head")
          else
            BRANCH_REFS+=("${{ github.ref }}")
          fi

          echo "Refs to clean: ${BRANCH_REFS[@]}"

          # Don't fail the workflow if cache deletion fails
          set +e

          for ref in "${BRANCH_REFS[@]}"; do
            echo "Fetching cache keys for ref: $ref"
            cacheKeys=$(gh actions-cache list -R "$REPO" -B "$ref" | cut -f 1)

            if [[ -z "$cacheKeys" ]]; then
              echo "No cache keys found for ref: $ref"
              continue
            fi

            echo "Deleting caches for ref: $ref"
            while IFS= read -r cacheKey; do
              gh actions-cache delete "$cacheKey" -R "$REPO" -B "$ref" --confirm
            done <<< "$cacheKeys"
          done

          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
