name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - uses: actions/checkout@v6
      - name: Add problem matchers
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔠 Lint project
        run: pnpm lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🌐 Install browser
        run: pnpm playwright install

      - name: 💪 Type check
        run: pnpm test:types

      - name: 🧪 Unit test
        run: pnpm test:unit

      - name: 🏃 Component tests
        run: pnpm test:nuxt

  browser:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🖥️ Test project (browser)
        run: pnpm test:browser

  a11y:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🏗️ Build project
        run: pnpm build

      - name: ♿ Accessibility audit (Lighthouse)
        run: pnpx @lhci/cli autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
