name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.repository_owner == 'wolfstar-project'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.14.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma types
        run: pnpm prisma:generate

      - name: Build & Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          project-key: wolfstar-rocks-24js
          build-command: pnpm build
